# Generated by Django 5.0.2 on 2024-04-01 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('Word', 'Word Document'), ('JPEG', 'JPEG Image')], max_length=10)),
                ('genre', models.CharField(choices=[('Physics', 'Physics'), ('History', 'History'), ('Literature', 'Literature'), ('Medicine', 'Medicine'), ('Technology', 'Technology'), ('Chemistry', 'Chemistry'), ('Arts', 'Arts'), ('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Computing', 'Computing')], max_length=50)),
                ('file', models.FileField(upload_to='archives/')),
                ('preview_image', models.ImageField(upload_to='previews/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('Author', 'Author'), ('Normal User', 'Normal User')], max_length=30)),
                ('profile_image', models.ImageField(default='profile/a.png', null=True, upload_to='profile/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
